"""initial schema

Revision ID: c34986b5a436
Revises: 
Create Date: 2026-04-02 00:06:20.538262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c34986b5a436'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('yahoo_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('alphavantage_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('finnhub_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('outlier_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources_available', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_symbol'), 'price_history', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('strategy_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starting_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aggregated_pnl',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('num_trades', sa.Integer(), nullable=False),
    sa.Column('num_wins', sa.Integer(), nullable=False),
    sa.Column('num_losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('starting_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ending_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregated_pnl_session_id'), 'aggregated_pnl', ['session_id'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=4), nullable=False),
    sa.Column('signal_reason', sa.String(length=255), nullable=False),
    sa.Column('price_at_signal', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('timestamp_open', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('timestamp_close', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('price_at_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_session_id'), 'paper_trades', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_trades_session_id'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_aggregated_pnl_session_id'), table_name='aggregated_pnl')
    op.drop_table('aggregated_pnl')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_symbol'), table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###
